version: '3'

services:
    web:
        build: .
        ports:
          - "9082:80"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
        links:
          - mysql

    mysql:
        image: bitnami/mysql:latest
        environment: 
          - ALLOW_EMPTY_PASSWORD=yes
          - MYSQL_ROOT_PASSWORD=